# Generated by Django 6.0.5 on 2026-05-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("local_clone_path", models.CharField(blank=True, max_length=1024)),
                ("default_branch", models.CharField(default="main", max_length=255)),
                ("last_indexed_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
